plugins {
    id 'java-library'
    id 'com.diffplug.spotless' version '8.10.2'
}

group = 'kg.aidarbek'
version = '1.0-SNAPSHOT'
description = 'A lightweight Java SMPP library'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
    withSourcesJar()
    withJavadocJar()
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:6.0.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation 'com.tngtech.archunit:archunit:1.4.2'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

spotless {
    java {
        target 'src/*/java/**/*.java'
        encoding 'UTF-8'
        lineEndings = com.diffplug.spotless.LineEnding.UNIX
        palantirJavaFormat('2.96.0')
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = 21
    options.compilerArgs.addAll(['-Xlint:all', '-Werror'])
}

tasks.withType(Javadoc).configureEach {
    options.encoding = 'UTF-8'
    options.docEncoding = 'UTF-8'
    options.charSet = 'UTF-8'
}

tasks.withType(AbstractArchiveTask).configureEach {
    preserveFileTimestamps = false
    reproducibleFileOrder = true
}

tasks.withType(Test).configureEach {
    useJUnitPlatform()
    testLogging {
        events 'failed', 'skipped'
        exceptionFormat = 'full'
    }
}
